### ISSUE TITLE
Cannot define OVSBOOTPROTO in RedHat

### ISSUE THREAD

**Issue by actatux** [example42/puppet-network#150]
## Expected Behavior 

A RedHat host  using openvswitch must be able to use DHCP to configure the OVSBridge.

From https://github.com/osrg/openvswitch/blob/master/rhel/README.RHEL

Enable DHCP on the bridge:
* **Needs OVSBOOTPROTO instead of BOOTPROTO.**
* All the interfaces that can reach the DHCP server
as a space separated list in OVSDHCPINTERFACES.

DEVICE=ovsbridge0
ONBOOT=yes
DEVICETYPE=ovs
TYPE=OVSBridge
**OVSBOOTPROTO="dhcp"**
OVSDHCPINTERFACES="eth0"
HOTPLUG=no

We need to add a new parameter to define the OVSBOOTPROTO.

## Actual Behavior
With the following hiera configuration, the DHCP does not work on the host, leading to loss of the network once the service is restarted.

```
network::interfaces_hash:
  enp1s0f0:
    devicetype: 'ovs'
    type: 'OVSPort'
    ovs_bridge: 'br0'
    ovs_options: "vlan_mode=native-untagged"
  br0:
    devicetype: 'ovs'
    type: 'OVSBridge'
    ovsdhcpinterfaces: 'enp1s0f0'
```

## Specifications

The PR is coming.
