### ISSUE TITLE
metric should be an array not integer

### ISSUE THREAD

**Issue by johnwarburton** [example42/puppet-network#192]
## Expected Behavior 
Tested by changing check to array;
```
Notice: /Stage[main]/Network/Network::Route[p257p8]/File[ifroute-eth88]/content: 
--- /etc/sysconfig/network/ifroute-eth88	2018-01-02 14:56:28.194719606 +1100
+++ /tmp/puppet-file20180104-21385-11tal9t	2018-01-04 08:18:01.074937431 +1100
@@ -1,6 +1,7 @@
 ###
 #### File managed by Puppet
 ####
+default 10.10.10.1 - eth88 metric 102
 default 10.10.10.1 - eth88 table internal2
 10.10.10.0 10.10.10.1 24 eth88 table internal2
```

## Actual Behavior
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, validate_integer(): Expected element at array position 1 to be an Integer, got String at /etc/puppetlabs/code/modules/network/manifests/route.pp:120:5 

## Steps to Reproduce the Problem
Create a route hash entry
```
network::routes_hash:
  eth88:
    ipaddress:
      - 'default'
      - 'default'
      - 10.10.10.0
    netmask:
      - '-'
      - '-'
      - 24
    gateway:
      - '10.10.10.1'
      - '10.10.10.1'
      - '10.10.10.1'
    table:
      - false
      - 'internal2'
      - 'internal2'
    metric:
      - 102
      - false
      - false
```

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)
```
os => {
  architecture => "x86_64",
  distro => {
    codename => "n/a",
    description => "SUSE Linux Enterprise Server 12 SP3",
    id => "SUSE",
    release => {
      full => "12.3",
      major => "12",
      minor => "3"
    },
    specification => "n/a"
  },
  family => "Suse",
  hardware => "x86_64",
  name => "SLES",
  release => {
    full => "12.3",
    major => "12",
    minor => "3"
  },

```
  1. Version of Puppet and of the module
Puppet client & server version: 4.5.2

  1. The relevant Puppet code and eventually Hiera data
see above
